- room: wohnzimmer
  lights: ["1", "2"]
- room: buero_merja
  lights: ["1", "2"]
- room: buero_fabian
  lights: ["1"]
- room: flur
  lights: ["1", "2", "3", "4", "5", "6"]
- room: kueche
  lights: ["1", "2", "3"]
- room: speisekammer
  lights: ["1", "2"]
- room: schlafzimmer
  lights: ["1", "2"]
- room: bad
  lights: ["1"]
  waterHigh: 800